CI and release improvements
**CI Improvements:**

* Test on the last 3 major OTP versions, following the Erlang/OTP support conventions.
* Test on Both Linux and OSX for each version
* Report test failures with JUnit, allowing to identify flaky tests
* Smoke test releases on all OSes and Erlang/OTP versions and add more extensive smoke test by publishing/subscribing to messages.

**Release Improvements:**

* Fixes release configuration problems in OSX in OTP 23 and 24
* Fixes release configuration problems when using Unix domain sockets
* Upgrade to Rebar3 1.19.x
* Releases can now build on OTP 25
* Releases can now build on ARM architectures (Tested on M1 Mac and Raspberry PI)

**Maintenance Improvements**

* Use new OTP 25 peer module to allow tests running in OTP25.
* Removes any master/slave terminologies for more inclusive language. Still the main branch is `master`, we probably should switch to `main`.
* Fixes some flaky tests, skipped some in CI, yet there are some flaky tests that are repoprted in GHA, need to aim for 0.
* Fix some unused variable warnings

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -1,3 +1,4 @@
+---
 name: Checks for a PR
 
 on:
@@ -5,30 +6,55 @@ on:
     branches:
       - master
 
+concurrency:
+  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
+  cancel-in-progress: true
+
+env:
+  # Default OTP version used for current releases
+  DEFAULT_RELEASE_OTP: 23.2.1
+
 jobs:
   code_checks:
     name: Check code style and quality
-    runs-on: ubuntu-18.04
+    runs-on: ubuntu-20.04
     steps:
-      - uses: actions/checkout@v2.0.0
+      - name: Install dependencies
+        run: |
+          sudo apt-get install -y cmake
+      - name: Checkout code
+        uses: actions/checkout@v3
       - name: Cache PLTs
         id: cache-plts
-        uses: actions/cache@v2
+        uses: actions/cache@v3
         with:
           path: |
             plts
             plts_base
-          key: ${{ runner.os }}-erlang-${{ hashFiles(format('{0}{1}', github.workspace, '/rebar.lock')) }}
-      - run: sudo apt-get -y install libsnappy-dev
-      - uses: erlef/setup-beam@v1
+          key: plts-cache-${{ runner.os }}-otp-${{env.DEFAULT_RELEASE_OTP}}-hash-${{hashFiles('rebar.lock')}}
+      - name: Cache _build/default
+        uses: actions/cache@v3
         with:
-          otp-version: 23.2.1
+          path: _build/default
+          key: _build_default-cache-${{runner.os}}-otp-${{env.DEFAULT_RELEASE_OTP}}-v2-hash-${{hashFiles('rebar.lock')}}
+      - name: Cache rebar3
+        uses: actions/cache@v3
+        with:
+          path: ~/.cache/rebar3
+          key: rebar3-cache-${{runner.os}}-otp-${{env.DEFAULT_RELEASE_OTP}}-v2-hash-${{hashFiles('rebar.lock')}}
+      - name: Install Erlang/OTP
+        uses: erlef/setup-beam@v1.15
+        with:
+          otp-version: ${{ env.DEFAULT_RELEASE_OTP }}
       - name: Check code formatting (erlfmt)
         run: ./rebar3 fmt -c
       - name: Run dialyzer type checker
         run: ./rebar3 dialyzer
+
   coverage:
-    runs-on: ubuntu-18.04
+    name: Run tests with coverage
+    runs-on: ubuntu-20.04
+    timeout-minutes: 60
     services:
       postgres:
         image: postgres
@@ -72,62 +98,170 @@ jobs:
           --health-timeout 5s
           --health-retries 5
     steps:
-      - uses: actions/checkout@v2.0.0
-      - run: sudo apt-get -y install libsnappy-dev
-      - uses: erlef/setup-beam@v1
+      - name: Install dependencies
+        run: |
+          sudo apt-get install -y cmake
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Install Erlang/OTP
+        uses: erlef/setup-beam@v1.15
         with:
-          otp-version: 23.2.1
-      - run: ./rebar3 as ci_tests do eunit --cover, ct --cover
+          otp-version: ${{ env.DEFAULT_RELEASE_OTP }}
+      - name: Cache _build/default
+        uses: actions/cache@v3
+        with:
+          path: _build/default
+          key: _build_default-cache-${{runner.os}}-otp-${{env.DEFAULT_RELEASE_OTP}}-v2-hash-${{hashFiles('rebar.lock')}}
+      - name: Cache rebar3
+        uses: actions/cache@v3
+        with:
+          path: ~/.cache/rebar3
+          key: rebar3-cache-${{runner.os}}-otp-${{env.DEFAULT_RELEASE_OTP}}-v2-hash-${{hashFiles('rebar.lock')}}
+      - name: Compile
+        run: ./rebar3 compile
+      - name: Run Tests
+        run: |
+          ./rebar3 as ci_tests,test do eunit --cover, ct --cover
       - run: ./rebar3 cover --verbose
       - name: Archive coverage report
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v3
         with:
           name: coverage-report
           path: _build/ci_tests+test/cover/
+          if-no-files-found: warn # do not fail if no coverdata found
           retention-days: 5
-      - name: CT test report
-        uses: actions/upload-artifact@v2
+      - name: Compress CT test report
+        if: ${{ ! cancelled() }}
+        run: |
+          tar -czf ct_test_report.tar.gz _build/ci_tests+test/logs/
+      - name: Archive CT test report
+        uses: actions/upload-artifact@v3
+        if: ${{ ! cancelled() }}
         with:
           name: ct-test-report
-          if: always()
-          path: _build/ci_tests+test/logs/
+          path: ct_test_report.tar.gz
           retention-days: 5
-  release-smoke-test:
-    runs-on: ubuntu-latest
-    container:
-      image: erlang:23-slim
+
+  tests:
+    name: Test on ${{ matrix.os }} with OTP ${{ matrix.otp }}
+    runs-on: ${{ matrix.os }}
+
+    # Fail if test takes over an hour
+    timeout-minutes: 60
+
+    strategy:
+      fail-fast: false
+      matrix:
+        os:
+          - ubuntu-20.04
+          # Monterrey
+          - macos-12
+        otp:
+          - "25.2"
+          - "24.3"
+          - "23.3"
+
     steps:
-      - run: apt-get update && apt-get -y install make libsnappy-dev git netcat gcc g++ curl libssl-dev
-      - uses: actions/checkout@v2.0.0
+      - name: Install dependencies (Linux)
+        if: ${{ startsWith(matrix.os, 'ubuntu') }}
+        run: |
+          sudo apt-get -qq update
+          sudo apt-get -qq install cmake mosquitto-clients
+      - name: Configure Homebrew cache
+        if: ${{ startsWith(matrix.os, 'macos') }}
+        uses: actions/cache@v3
+        with:
+          path: |
+            ~/Library/Caches/Homebrew/
+            ~/Library/Caches/Homebrew/downloads/
+          key: brew-${{ runner.os }}-${{ matrix.otp  }}
+      - name: Install Dependencies (OSX)
+        if: ${{ startsWith(matrix.os, 'macos') }}
+        run: |
+          export majorversion="$(cut -d '.' -f 1 <<< "${{ matrix.otp }}")"
+          brew install coreutils erlang@$majorversion openssl mosquitto
+          echo "/usr/local/opt/erlang@$majorversion/bin" >> $GITHUB_PATH
+      - name: Checkout code
+        uses: actions/checkout@v3
         with:
           fetch-depth: 0
-      - name: Fetch tags
-        run: git fetch --tags
-      - name: Build release
-        run: make rel
-      - name: Start release
-        run: ./_build/default/rel/vernemq/bin/vernemq start
-      - name: Wait up to 5 minutes for MQTT port to come up
-        run: timeout 300 sh -c 'until nc -z $0 $1; do sleep 1; done' localhost 1883
-      - name: Ping the server
-        run: ./_build/default/rel/vernemq/bin/vernemq ping
-      - name: Stop the server
-        run: ./_build/default/rel/vernemq/bin/vernemq stop
-  matrix:
-    runs-on: ubuntu-18.04
-    strategy:
-      matrix:
-        erlang: ["22.0", "23.0", "24.0", "24.3.3"]
-    steps:
-      - uses: actions/checkout@v2.0.0
-      - uses: erlef/setup-beam@v1
+      - name: Install Erlang/OTP
+        # setup beam doesn't provide MacOS packages
+        # we use Homebrew to instal them
+        if: ${{ !startsWith(matrix.os , 'macos') }}
+        uses: erlef/setup-beam@v1.15
         with:
-          otp-version: ${{ matrix.erlang }}
-      - run: sudo apt-get -y install libsnappy-dev
-      - run: ./rebar3 do eunit, ct
-  macos:
-    runs-on: macos-latest
+          otp-version: ${{ matrix.otp }}
+          version-type: strict
+      - name: Cache build
+        uses: actions/cache@v3
+        with:
+          path: _build/default
+          key: ${{ runner.os }}-build-default-${{ matrix.otp }}-v2-${{ hashFiles(format('rebar.lock')) }}
+      - name: Cache rebar3
+        uses: actions/cache@v3
+        with:
+          path: ~/.cache/rebar3
+          key: ${{runner.os}}-rebar3-${{matrix.otp}}-v2-${{ hashFiles(format('rebar.lock')) }}
+      - name: Compile
+        run: ./rebar3 compile
+      - name: Run tests
+        run: |
+          ./rebar3 do eunit, ct
+      - name: Upload JUnit Test Report
+        uses: actions/upload-artifact@v3
+        if: always() # always run even if the previous step fails
+        with:
+          name: junit-test-results
+          path: "**/_build/test/logs/*/junit_report.xml"
+          retention-days: 1
+      - name: Release Smoke tests
+        run: |
+          # Release and Start the server
+          make rel
+          # Debug any configuration problem before release starts
+          ./_build/default/rel/vernemq/bin/vernemq config generate -l debug
+          # Allow anonymous connections
+          echo "allow_anonymous = on" >> _build/default/rel/vernemq/etc/vernemq.conf
+          ./_build/default/rel/vernemq/bin/vernemq start
+          # Wait for port to come up
+          timeout 300 sh -c 'until nc -z $0 $1; do sleep 1; done' localhost 1883
+          # Ping the server
+          ./_build/default/rel/vernemq/bin/vernemq ping | grep -q pong
+          # Simple publish/subscribe test
+          mosquitto_sub -p 1883 -W 1 -C 1 -t 'tests/simple' >/dev/null &
+          export SUB_PID=$!
+          mosquitto_pub -p 1883 -t 'tests/simple' -m 'simple-test'
+          kill ${SUB_PID} 2>/dev/null || true
+          echo "Simple publish/subscribe: ok"
+          # Multiple publish/subscribe test (Send each line on a file)
+          export EXPECT_MSGS=$(wc -l ./THANKS | cut -d' ' -f1)
+          mosquitto_sub -p 1883 -W 1 -C ${EXPECT_MSGS} -t 'tests/multi' >/dev/null &
+          export SUB_PID=$!
+          mosquitto_pub -p 1883 -t 'tests/multi' -f ./THANKS
+          kill ${SUB_PID} 2>/dev/null || true
+          echo "Multiple publish/subscribe: ok"
+          # Stop the server
+          ./_build/default/rel/vernemq/bin/vernemq stop
+
+  publish-test-results:
+    name: Publish Tests Results
+    needs: tests
+    runs-on: ubuntu-20.04
+    permissions:
+      checks: write
+    if: always()
+
     steps:
-      - uses: actions/checkout@v2.0.0
-      - run: brew install erlang snappy
-      - run: ./rebar3 do eunit, ct
+      - name: Download Artifacts
+        uses: actions/download-artifact@v3
+        with:
+          path: junit-test-results
+
+      - name: Publish CT Test Results
+        uses: EnricoMi/publish-unit-test-result-action@v2
+        with:
+          check_name: CT Test Results
+          # Do not comment on PRs
+          comment_mode: off
+          junit_files: "**/_build/test/logs/*/junit_report.xml"
